import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

export default function RootLayout ({ 
    children,
    metaTitle,
 }: {
    children: React.ReactNode,
    metaTitle?: string
 }) {
    return (
        <>
        <Head>
            <title>{`tittel ${metaTitle || ''}`}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
            className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
        >
            <Header />
            <div className="flex-1 flex items-center justify-center">{children}</div>
            <Footer />
        </div>
        </>
    )
}